import Modal from "../components/Modal";
import Button from "../components/Button";
import { useState } from "react";

function ModalPage(){
    const [showModal , setShowModal] = useState(false)
    const handleClick = () => {
        setShowModal(true)
    }
    const handleClose = () => {
        setShowModal(false);
    }
    const modal =  <Modal onClose ={handleClose} actionBar = {<Button primary onClick={handleClose} >Click Yes</Button>} >
     <p>here is an imp msg</p>
     </Modal>
    
    return <div>
    
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc scelerisque at ante consequat tristique. Quisque venenatis, mi vel tincidunt pretium, quam orci imperdiet elit, a suscipit odio nisl eget nisi. Ut elit felis, eleifend a tortor eget, feugiat tempor est. Vestibulum commodo dapibus mauris elementum facilisis. Sed porttitor urna arcu, vel posuere eros imperdiet ut. Integer euismod quis tortor sed pharetra. Quisque varius et lectus vel commodo. Sed maximus purus et faucibus lacinia. Quisque a metus ac magna venenatis feugiat et vel magna. Duis rhoncus laoreet orci, et tempus mi placerat quis. Nulla facilisi. Donec ut nisi ornare, varius dui in, consequat purus. In non velit nec nulla imperdiet efficitur ac in erat. Vestibulum volutpat orci pharetra pellentesque sodales. Duis condimentum ex feugiat nibh cursus, vitae dictum leo scelerisque. Nullam id justo tempus, elementum massa ut, finibus nibh.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc scelerisque at ante consequat tristique. Quisque venenatis, mi vel tincidunt pretium, quam orci imperdiet elit, a suscipit odio nisl eget nisi. Ut elit felis, eleifend a tortor eget, feugiat tempor est. Vestibulum commodo dapibus mauris elementum facilisis. Sed porttitor urna arcu, vel posuere eros imperdiet ut. Integer euismod quis tortor sed pharetra. Quisque varius et lectus vel commodo. Sed maximus purus et faucibus lacinia. Quisque a metus ac magna venenatis feugiat et vel magna. Duis rhoncus laoreet orci, et tempus mi placerat quis. Nulla facilisi. Donec ut nisi ornare, varius dui in, consequat purus. In non velit nec nulla imperdiet efficitur ac in erat. Vestibulum volutpat orci pharetra pellentesque sodales. Duis condimentum ex feugiat nibh cursus, vitae dictum leo scelerisque. Nullam id justo tempus, elementum massa ut, finibus nibh.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc scelerisque at ante consequat tristique. Quisque venenatis, mi vel tincidunt pretium, quam orci imperdiet elit, a suscipit odio nisl eget nisi. Ut elit felis, eleifend a tortor eget, feugiat tempor est. Vestibulum commodo dapibus mauris elementum facilisis. Sed porttitor urna arcu, vel posuere eros imperdiet ut. Integer euismod quis tortor sed pharetra. Quisque varius et lectus vel commodo. Sed maximus purus et faucibus lacinia. Quisque a metus ac magna venenatis feugiat et vel magna. Duis rhoncus laoreet orci, et tempus mi placerat quis. Nulla facilisi. Donec ut nisi ornare, varius dui in, consequat purus. In non velit nec nulla imperdiet efficitur ac in erat. Vestibulum volutpat orci pharetra pellentesque sodales. Duis condimentum ex feugiat nibh cursus, vitae dictum leo scelerisque. Nullam id justo tempus, elementum massa ut, finibus nibh.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc scelerisque at ante consequat tristique. Quisque venenatis, mi vel tincidunt pretium, quam orci imperdiet elit, a suscipit odio nisl eget nisi. Ut elit felis, eleifend a tortor eget, feugiat tempor est. Vestibulum commodo dapibus mauris elementum facilisis. Sed porttitor urna arcu, vel posuere eros imperdiet ut. Integer euismod quis tortor sed pharetra. Quisque varius et lectus vel commodo. Sed maximus purus et faucibus lacinia. Quisque a metus ac magna venenatis feugiat et vel magna. Duis rhoncus laoreet orci, et tempus mi placerat quis. Nulla facilisi. Donec ut nisi ornare, varius dui in, consequat purus. In non velit nec nulla imperdiet efficitur ac in erat. Vestibulum volutpat orci pharetra pellentesque sodales. Duis condimentum ex feugiat nibh cursus, vitae dictum leo scelerisque. Nullam id justo tempus, elementum massa ut, finibus nibh.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc scelerisque at ante consequat tristique. Quisque venenatis, mi vel tincidunt pretium, quam orci imperdiet elit, a suscipit odio nisl eget nisi. Ut elit felis, eleifend a tortor eget, feugiat tempor est. Vestibulum commodo dapibus mauris elementum facilisis. Sed porttitor urna arcu, vel posuere eros imperdiet ut. Integer euismod quis tortor sed pharetra. Quisque varius et lectus vel commodo. Sed maximus purus et faucibus lacinia. Quisque a metus ac magna venenatis feugiat et vel magna. Duis rhoncus laoreet orci, et tempus mi placerat quis. Nulla facilisi. Donec ut nisi ornare, varius dui in, consequat purus. In non velit nec nulla imperdiet efficitur ac in erat. Vestibulum volutpat orci pharetra pellentesque sodales. Duis condimentum ex feugiat nibh cursus, vitae dictum leo scelerisque. Nullam id justo tempus, elementum massa ut, finibus nibh.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc scelerisque at ante consequat tristique. Quisque venenatis, mi vel tincidunt pretium, quam orci imperdiet elit, a suscipit odio nisl eget nisi. Ut elit felis, eleifend a tortor eget, feugiat tempor est. Vestibulum commodo dapibus mauris elementum facilisis. Sed porttitor urna arcu, vel posuere eros imperdiet ut. Integer euismod quis tortor sed pharetra. Quisque varius et lectus vel commodo. Sed maximus purus et faucibus lacinia. Quisque a metus ac magna venenatis feugiat et vel magna. Duis rhoncus laoreet orci, et tempus mi placerat quis. Nulla facilisi. Donec ut nisi ornare, varius dui in, consequat purus. In non velit nec nulla imperdiet efficitur ac in erat. Vestibulum volutpat orci pharetra pellentesque sodales. Duis condimentum ex feugiat nibh cursus, vitae dictum leo scelerisque. Nullam id justo tempus, elementum massa ut, finibus nibh.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc scelerisque at ante consequat tristique. Quisque venenatis, mi vel tincidunt pretium, quam orci imperdiet elit, a suscipit odio nisl eget nisi. Ut elit felis, eleifend a tortor eget, feugiat tempor est. Vestibulum commodo dapibus mauris elementum facilisis. Sed porttitor urna arcu, vel posuere eros imperdiet ut. Integer euismod quis tortor sed pharetra. Quisque varius et lectus vel commodo. Sed maximus purus et faucibus lacinia. Quisque a metus ac magna venenatis feugiat et vel magna. Duis rhoncus laoreet orci, et tempus mi placerat quis. Nulla facilisi. Donec ut nisi ornare, varius dui in, consequat purus. In non velit nec nulla imperdiet efficitur ac in erat. Vestibulum volutpat orci pharetra pellentesque sodales. Duis condimentum ex feugiat nibh cursus, vitae dictum leo scelerisque. Nullam id justo tempus, elementum massa ut, finibus nibh.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc scelerisque at ante consequat tristique. Quisque venenatis, mi vel tincidunt pretium, quam orci imperdiet elit, a suscipit odio nisl eget nisi. Ut elit felis, eleifend a tortor eget, feugiat tempor est. Vestibulum commodo dapibus mauris elementum facilisis. Sed porttitor urna arcu, vel posuere eros imperdiet ut. Integer euismod quis tortor sed pharetra. Quisque varius et lectus vel commodo. Sed maximus purus et faucibus lacinia. Quisque a metus ac magna venenatis feugiat et vel magna. Duis rhoncus laoreet orci, et tempus mi placerat quis. Nulla facilisi. Donec ut nisi ornare, varius dui in, consequat purus. In non velit nec nulla imperdiet efficitur ac in erat. Vestibulum volutpat orci pharetra pellentesque sodales. Duis condimentum ex feugiat nibh cursus, vitae dictum leo scelerisque. Nullam id justo tempus, elementum massa ut, finibus nibh.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc scelerisque at ante consequat tristique. Quisque venenatis, mi vel tincidunt pretium, quam orci imperdiet elit, a suscipit odio nisl eget nisi. Ut elit felis, eleifend a tortor eget, feugiat tempor est. Vestibulum commodo dapibus mauris elementum facilisis. Sed porttitor urna arcu, vel posuere eros imperdiet ut. Integer euismod quis tortor sed pharetra. Quisque varius et lectus vel commodo. Sed maximus purus et faucibus lacinia. Quisque a metus ac magna venenatis feugiat et vel magna. Duis rhoncus laoreet orci, et tempus mi placerat quis. Nulla facilisi. Donec ut nisi ornare, varius dui in, consequat purus. In non velit nec nulla imperdiet efficitur ac in erat. Vestibulum volutpat orci pharetra pellentesque sodales. Duis condimentum ex feugiat nibh cursus, vitae dictum leo scelerisque. Nullam id justo tempus, elementum massa ut, finibus nibh.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc scelerisque at ante consequat tristique. Quisque venenatis, mi vel tincidunt pretium, quam orci imperdiet elit, a suscipit odio nisl eget nisi. Ut elit felis, eleifend a tortor eget, feugiat tempor est. Vestibulum commodo dapibus mauris elementum facilisis. Sed porttitor urna arcu, vel posuere eros imperdiet ut. Integer euismod quis tortor sed pharetra. Quisque varius et lectus vel commodo. Sed maximus purus et faucibus lacinia. Quisque a metus ac magna venenatis feugiat et vel magna. Duis rhoncus laoreet orci, et tempus mi placerat quis. Nulla facilisi. Donec ut nisi ornare, varius dui in, consequat purus. In non velit nec nulla imperdiet efficitur ac in erat. Vestibulum volutpat orci pharetra pellentesque sodales. Duis condimentum ex feugiat nibh cursus, vitae dictum leo scelerisque. Nullam id justo tempus, elementum massa ut, finibus nibh.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc scelerisque at ante consequat tristique. Quisque venenatis, mi vel tincidunt pretium, quam orci imperdiet elit, a suscipit odio nisl eget nisi. Ut elit felis, eleifend a tortor eget, feugiat tempor est. Vestibulum commodo dapibus mauris elementum facilisis. Sed porttitor urna arcu, vel posuere eros imperdiet ut. Integer euismod quis tortor sed pharetra. Quisque varius et lectus vel commodo. Sed maximus purus et faucibus lacinia. Quisque a metus ac magna venenatis feugiat et vel magna. Duis rhoncus laoreet orci, et tempus mi placerat quis. Nulla facilisi. Donec ut nisi ornare, varius dui in, consequat purus. In non velit nec nulla imperdiet efficitur ac in erat. Vestibulum volutpat orci pharetra pellentesque sodales. Duis condimentum ex feugiat nibh cursus, vitae dictum leo scelerisque. Nullam id justo tempus, elementum massa ut, finibus nibh.</p>
    
    <Button primary onClick = {handleClick}>open Modal!</Button>
    {showModal && modal}
    
</div>
}

export default ModalPage;